(function($, window, document, undefined) {

    var people = [
        {"id":1,"group":"Cast","name":"Miriam Aslam","role":"Mama Ogre, Fairytale Creature","grade":"8","bio":"This is my third year performing in RBMS plays. I was Orphan Kate in Annie and a Lioness in <em>The Lion King</em>. When I’m not on stage I enjoy singing, dancing and playing the piano. I would like to thank Mr. Simonton, the tech crew and my family and friends for support.",},
        {"id":2,"group":"Cast","name":"Austin Taylor","role":"Papa Ogre, Fairytale Creature","grade":"8","bio":"You'll remember me from <em>The Lion King</em>, Jr. last year when I played the fun-loving Pumbaa. This year I'm honored to be playing Papa Ogre in <em>Shrek Jr.</em> I've also enjoyed the opportunity to take the first Exploratory Dramatics class here at River Bend, and I look forward to continuing my study of theater next year at Potomac Falls!  My hobbies outside of school include making YouTube videos, drawing and creative writing. I would like to thank my family for their support. Enjoy the show! ",},
        {"id":3,"group":"Cast","name":"Elizabeth Dykes","role":"Child Shrek, Fairytale Creature","grade":"6","bio":"I am super exited to be playing the role of young Shrek. This is the first play that I will be in with my sister, Ani. I had a lot of fun at rehearsal with a bunch of my friends. I have made a bunch of new friends because of the play. Enjoy the show!!!",},
        {"id":4,"group":"Cast","name":"Henry Gregory","role":"Shrek","grade":"8","bio":"This is Henry's 4th musical theater production. He loves the stage, but he also enjoys music just as much. Henry plays piano and likes to mess around with the guitar. His favorite band is Queen. When he's not on stage, you're most likely to find him singing Freddie Mercury tunes on the piano at home, watching YouTube, or hanging out with his friends.",},
        {"id":5,"group":"Cast","name":"Ben Shumaker","role":"Captain of the Guard, Knight","grade":"7","bio":"I am so happy to be the Captain of the Guards this year. This is my second production here at River Bend&mdash;I was part of the ensemble last year in <em>The Lion King</em>. I have wanted to be an actor for so long, so I am so happy to get a chance to act in front of so many people. I want to thank Mr. Simonton for being a great teacher and director, putting in so much effort for this performance.",},
        {"id":6,"group":"Cast","name":"Emilio Naranjo","role":"Pinocchio","grade":"8","bio":"I started acting in the 6th grade production of Annie Jr. as a house servant, and followed in the 7th grade production of <em>The Lion King Jr.</em> as a vulture. I am thrilled to play the role of Pinocchio in this years' production of <em>Shrek Jr.</em> Moving up from chorus was a big step, but it shall all be worth it in the end. During my spare time, I enjoy drawing comics, playing video games, and spending time with friends and family.  I'd like to thank my parents and Mr. Simonton for their support.",},
        {"id":7,"group":"Cast","name":"Nicole Babb","role":"Pig #1","grade":"6","bio":"I am so excited to be a part of <em>Shrek Jr.</em>, The Musical during my first year of middle school. While attending Potowmack Elementary, I played the role of Mrs. Beauregarde in <em>Willy Wonka and the Chocolate Factory</em>. In my spare time, I like to sing and dance. I especially love line dancing! It was a lot of fun working with the cast, choreographers, and Mr. Simonton. I hope everyone enjoys our performance!",},
        {"id":8,"group":"Cast","name":"Kyla Lee","role":"Pig #2","grade":"8","bio":"Kyla is playing the role of Pig #2 in <em>Shrek Jr.</em> Last year she played a wildebeast in <em>The Lion King Jr.</em> Kyla has also been in chorus for three years and Raven Choir for two years. She plans on being in show choir in high school. Outside of school, Kyla likes to play soccer, go to the mall with friends and foster animals. Kyla is starting to explore interior design, which is what she wants to study in college. She would like to thank her friends and family for their support and Mr Simonton for his hard work.",},
        {"id":9,"group":"Cast","name":"Leanne Rogers","role":"Pig #3","grade":"8","bio":"I am so excited to take part in this year’s production of <em>Shrek Jr.</em> as Pig #3. You may remember me from my notable roles in <em>Annie Jr.</em> (servant, street vendor) and <em>The Lion King Jr.</em> (human ensemble). When not hamming it up on stage, I have a blast playing the trumpet, playing soccer, and following all things SpaceX. I would like to thank Mr. Simonton for all his support during my time at River Bend and for making the theater productions such a wonderful experience. I will never forget it!",},
        {"id":10,"group":"Cast","name":"Samiha Hamzayeva","role":"Storyteller","grade":"7","bio":"I'm simply ecstatic to be playing the role of the Storyteller this year. I have previously cooperated in RBMS's <em>The Lion King Jr.</em> as a part of the ensemble, & am really loving the step-up. When not on stage, I execute being stressed very perfectly, & enjoy any other artistic activity (whether I'm good at it or not), working hard, & giving out free hugs. I'd like to thank Mr. Simonton for both casting me & putting up with the amazing cast and crew every year, & my family for their support.",},
        {"id":11,"group":"Cast","name":"Anna Messick","role":"Wicked Witch","grade":"7","bio":"I am so excited to be a part of this years production of <em>Shrek Jr.</em> as the Wicked Witch. Last year I played the part of Bonzai in <em>The Lion King Jr.</em> and loved being part of this River Bend Musical community. In my free time I love to sign, play volleyball and spend time with my friends. Big thanks to Mr. Simonton for taking on this big production and leading us the entire way.",},
        {"id":12,"group":"Cast","name":"Riti Liu","role":"Peter Pan","grade":"8","bio":"I'm so excited to participate in this year's production of <em>Shrek Jr.</em> as Peter Pan! I also appeared in the RBMS productions of <em>The Lion King Jr.</em> and <em>Annie</em>. In 5th grade, I played the part of Frog in the musical <em>Frog and Toad</em>. When not on stage, I enjoy singing, reading, spending time with friends, and playing field hockey. I would like to thank all of my family and friends who always support me. I'd also like to thank Mr. Simonton and the choreographers for working so hard on this year's performance.",},
        {"id":13,"group":"Cast","name":"Kylie Lewandowski","role":"Ugly Duckling","grade":"7","bio":"I have been in 12 musicals counting this one, including <em>School of Rock</em>, <em>Newsies</em>, and <em>Aladdin</em>. I love watching theatre productions, listening to soundtracks of musicals, but most of all, I love to perform! I have such a supporting family. Two amazing parents, an awesome brother, three great dogs, and an adorable gerbil. I was thrilled to learn that I would be collaborating and performing with such an amazing, talented cast. Thank you so much for this amazing opportunity!",},
        {"id":14,"group":"Cast","name":"Natalie Brown","role":"Mama Bear","grade":"6","bio":"Natalie’s love of theater started at five years old watching the Sterling Playmakers from the front row. Since then she has performed in <em>The Music Man</em>, <em>Oliver!</em>, <em>The Little Mermaid</em>, and <em>Beauty And The Beast</em>.",},
        {"id":15,"group":"Cast","name":"Kamron Abdulwaheed","role":"Papa Bear","grade":"6","bio":"(Don't try to pronounce my last name!) This guy laughs at everything, he's known as &ldquo;that one guy that did fortnite dances in the gym&rdquo; (literally I swear), &ldquo;oh my god his hair is getting so long!&rdquo;, and &ldquo;shut up Kamron&rdquo;. When not performing, he loves being as loud as physically possible and...animating stickmen? He loves drama and he would not know this without Mr. Simonton. Thank you.",},
        {"id":16,"group":"Cast","name":"Hali Moe","role":"Baby Bear","grade":"7","bio":"I am so excited to be playing baby bear this year in <em>Shrek Jr.</em>! In sixth grade, I was a dancer in <em>The Lion King</em> here at RBMS, and in fifth grade I was a lamp in <em>Aladdin</em>. When not in school, I go to dance every day and love to do art! I want to thank Mr. Simonton for the opportunity to star in this play, and my amazing sister, Emma, for inspiring me to join the play back in sixth grade!",},
        {"id":17,"group":"Cast","name":"Avery Medina","role":"Mad Hatter","grade":"6","bio":"<em>Shrek Jr.</em> is my 1st production at River Bend, although my parents say I've been entertaining since the day I was born. I absolutely love it! Outside of school, I've been on a competitive dance team for several years. Performing is definitely a passion of mine. I'd like to give a BIG SHOUT OUT to my family, Mr. Simonton, Ms. Amanda, Mrs. Rossi, the tech crew and all the cast- you guys are the BOMB DIGGITY!!",},
        {"id":18,"group":"Cast","name":"Arjun Setty","role":"Big Bad Wolf","grade":"7","bio":"I am thrilled to play the role of Big Bad Wolf in this years production of Shrek. Last year, I played the role of Young Simba in RBMS’ production of <em>The Lion King</em>. In 5th Grade at Potowmack Elementary School, I was Aladdin. I’d like to thank Mr. Simonton for teaching me acting through the Exploratory Dramatics Class and the rest of the musical volunteers for helping to put on this amazing production.",},
        {"id":19,"group":"Cast","name":"Raadiya Emran","role":"Donkey","grade":"6","bio":"I'm so excited to be playing the role of Donkey in <em>Shrek Jr.</em> Outside of theater I love to sing, read and play basketball (though I can't say I'm good at it). I'd like to thank my mom and my sisters for being so supportive and encouraging in my theater experience! Lastly, I would like to say thanks to Mr. Simonton for being an amazing, and humorous director!!",},
        {"id":20,"group":"Cast","name":"John Elieson","role":"Lord Farquaad","grade":"8","bio":"John is excited to be in his first musical this year.  Although he can usually be found shooting hoops, throwing a football around, or loving on his baby sister, his love for the stage, and singing finally has an outlet at River Bend's drama department.  He wants to thank his fearless director, Mr. Simonton, for giving him a shot and helping him develop his creative skills.",},
        {"id":21,"group":"Cast","name":"Trent Chemezov","role":"Gingy","grade":"6","bio":"I first discovered my interest for acting in first grade when I joined an Odyssey of the Mind group and made a &ldquo;play&rdquo;. Since then I have done a lot more Odyssey of the Mind, as well as theatre camps with Sterling Playmakers. I'm happy to be part of my first full production at River Bend. (Please note, my real voice is not at all like my Gingy voice on stage). I would like to thank my mom for doing all the costumes, and Mr. Simonton for taking his time to direct the musical.",},
        {"id":22,"group":"Cast","name":"Myla Harris","role":"Young Fiona","grade":"6","bio":"I am excited to play the role of Young Fiona. This will be my first musical, but not my last! I love singing and acting and playing softball. I would like to thank Mr. Simonton for casting me and my parents and brothers for all their love and support! ",},
        {"id":23,"group":"Cast","name":"Kiley Ensminger","role":"Teen Fiona","grade":"8","bio":"I am excited to be playing the part of Teen Fiona in this years production of <em>Shrek, Jr.</em> Last year I was a zebra in <em>The Lion King</em> and in 6th grade I was an orphan in <em>Annie Jr.</em> When not on stage, I enjoy singing, playing soccer, and being with friends and family. I would like to thank Mr. Simonton and all the volunteers that have helped with this play.",},
        {"id":24,"group":"Cast","name":"Lily Rossi","role":"Adult Fiona","grade":"8","bio":"Although Belle has been, and always will be, Lily’s favorite princess, she was more than excited to get the chance to play Adult Fiona in this year's RBMS production. She enjoys dancing at East Coast Edge, choreographing, and baking an impressive number of sweets. She would like to thank her family and friends for their support, her voice teacher Sarah for the tips, Mr. Simonton, and her dance friends and teachers for their endless laughter and kindness they have shown her throughout the process.",},
        {"id":25,"group":"Cast","name":"Ani Dykes","role":"Ogre Fiona, Duloc Performer","grade":"8","bio":"This is my third musical at River Bend. I have enjoyed working with my friends. I am very excited to be a part of <em>Shrek Jr.</em>! Thank you to the cast, crew, teachers and parents for all of their hard work to make this production successful.",},
        {"id":26,"group":"Cast","name":"Seth Elieson","role":"Knight #1","grade":"6","bio":"Seth has tried baseball, swimming, football and basketball, but nowhere do they call for expertise in goofing off like a monkey for the good of the team. Enter DRAMA! As his first musical, Seth is excited to sing songs he already knows, and hang out with friends and his brother. He wants to thank Salem, Ben and John for paving the way before him, and making performing look like a lot of fun.",},
        {"id":27,"group":"Cast","name":"Sophie Castillo","role":"Knight #2","grade":"8","bio":"I am thrilled to be playing the part of knight #2 in this year's musical <em>Shrek Jr.</em> I started theater this year and I am quite happy that I joined. I have loved acting since I was little and to be a part of this musical is truly an amazing opportunity! When off stage I enjoy drawing, singing, and playing the piano. Thank you to Mr. Simonton for putting up with all the drama kids shenanigans!",},
        {"id":28,"group":"Cast","name":"Jeremy LaFrancois","role":"Knight #3","grade":"6","bio":"Jeremy is a member of the drama club, an active Boy Scout, and participated in Odyssey of the Mind this year. In elementary school, Jeremy enjoyed participating in the class musicals. This is his first middle school production. He is very excited to be a part of the cast! In his free time, Jeremy likes to play video games.",},
        {"id":29,"group":"Cast","name":"Mason Saunders","role":"Knight #4","grade":"6","bio":"This is my first production at RBMS and I am excited to play one of the knights. I love acting and have been involved in theater for a few years. My biggest role was when I played Corny Collins in the musical <em>Hairspray Jr.</em> and have had supporting roles in <em>The Addams Family</em>, <em>Newsies</em>, <em>Descendants</em>, and was part of an improv group that created and performed SNL skits. I would like to thank my family for always believing in me and supporting my dreams as well as Mr. Simonton and the theater program.",},
        {"id":30,"group":"Cast","name":"Indira Langhum","role":"Dragon Lead","grade":"8","bio":"I am so excited to be playing the head of the dragon in this year’s production of <em>Shrek Jr.</em>! I would like to thank the entire cast, crew, and especially our director Mr. Simonton for working so incredibly hard on this show. When not on stage I love to dance, write poetry, watch movies with my family, and endlessly annoy my friends and older brother by constantly singing with or without my ukulele.",},
        {"id":31,"group":"Cast","name":"Lauren Ignazzitto","role":"Dragon Body","grade":"7","bio":"I’m so excited to be performing in <em>Shrek Jr.</em> this year. I loved performing in last year’s production of <em>The Lion King Jr.</em> and had a lot of fun performing in <em>Aladdin Jr.</em> in 5th in grade. When I’m not on stage, I enjoy singing in Raven Choir, dancing, and hanging out with my friends. I would like to thank Mr. Simonton for casting me and my parents for their support.",},
        {"id":32,"group":"Cast","name":"Lexi Pantella","role":"Dragon Body","grade":"7","bio":"Lexi, naturally artistic, loves photography, drawing, montaging, calligraphy, reading, writing, singing and dancing. She is also an aspiring guitar player / song-writer, riffing in her spare time and kickin’ it in jam sessions with family and friends whenever she can. Though it has fallen off her cool scale, she still enjoys family game night and cracking a reticent smile at dad’s bad jokes. Lexi is a fiercely loyal friend, and so a perfect fit to play Dragon in this year’s <em>Shrek Jr.</em> production.",},
        {"id":33,"group":"Cast","name":"Myriam Elmi","role":"Dragon Body","grade":"8","bio":"Myriam Elmi has been performing in River Bend productions since she was in 6th grade. This is her final production as an 8th grader. She’d like to thank her family and friends and Mr. Simonton for all their support!",},
        {"id":34,"group":"Cast","name":"Landon Linn","role":"Pied Piper, Lord Farquaad (u/s)","grade":"8","bio":"I am playing the Pied Piper and am the understudy (and obviously better) Lord Farquaad. I would like to thank my parents for their support in working the musical in around everything else I do, and my friends in the crew and cast for their continual support throughout the musical. Outside of the stage, I dance ballet and hip hop and enjoy reading and sketching in my free time.",},
        {"id":35,"group":"Cast","name":"Emma Moe","role":"3 Blind Mice, Rat Dancer","grade":"8","bio":"I am very excited to be playing a blind mouse in this year's musical! Last year, I played Young Nala in <em>The Lion King</em>;. Also in that year, I was a giraffe and a grasslands dancer in my dance studio' production of <em>The Lion King</em>. In sixth grade, I played an orphan in <em>Annie</em>, and in fifth grade I was a bird in <em>A Year with Frog and Toad</em>. When not in school, I dance every day and like reading. I want to thank Mr. Simonton for the opportunity to be in this musical!",},
        {"id":36,"group":"Cast","name":"Vivian Wilkins","role":"3 Blind Mice, Rat Dancer","grade":"8","bio":"Hello everyone. I am happy to be a part of the <em>Shrek Jr</em> cast this year. I enjoy singing and dancing and will be one of the three blind mice. It will be my first performance at River Bend. I have performed with the Sterling Playmakers in <em>Oliver!</em>, <em>Beauty and the Beast</em> and the 42nd Street Kids Chorus. Many thanks to Mr Simonton and the tech crew for all the hard work and dedication. Sit back, relax, and enjoy the show!",},
        {"id":37,"group":"Cast","name":"Katie Moore","role":"3 Blind Mice, Rat Dancer","grade":"7","bio":"I’m excited this year to be in the <em>Shrek Jr</em> performance. I plan to do more with theater in the years to come! I would like to Thank my family for support and Mr. Simonton for this chance!!",},
        {"id":38,"group":"Cast","name":"Angelina McMahan","role":"3 Blind Mice, Rat Dancer","grade":"6","bio":"Angelina began dancing at age 2½ when she first posed with Angelina Ballerina at a PBS kids event. She has spent the next 10 years starring in the McMahan family room dazzling us with her joy, passion and love of Broadway musicals.  Angelina was most recently seen as a &ldquo;Modern&rdquo; in <em>Millie</em>, &ldquo;The Waves&rdquo; in <em>Moana</em>, and  &ldquo;&hellip; & Peggy!&rdquo; in the family production of <em>Hamilton</em>. Angelina is excited to join RBMS in the ensemble of <em>Shrek Jr.</em>  She dreams of one day getting &ldquo;Greenifyed&rdquo; in <em>Oz</em>.",},
        {"id":39,"group":"Cast","name":"Jackson Lenz","role":"Bishop","grade":"6","bio":"Jackson Lenz, who plays the role of the Bishop, is participating in his first acting experience. Jackson is a sixth grader at River Bend where his favorite subjects are Science and Chorus. When not at school, Jackson enjoys hanging out and playing various games with his family and friends.",},
        {"id":40,"group":"Cast","name":"Kellen Berger","role":"Dwarf","grade":"6","bio":"This is Kellen’s first show and he is very excited to be playing Dwarf. He’d like to thank Mr. Simonton for corralling the kids and helping us make a great show. He’d also like to thank his knee pads for helping him through rehearsals!",},
        {"id":41,"group":"Tech","name":"Angelica Franco Brito","role":"Tech Crew","grade":"8","bio":"I had a lot of fun in Tech Crew this year! I participated in Tech Crew last year and I really enjoyed it, so I participated again this year. In my free time, I enjoy playing the guitar, drawing, and writing. I want to thank everyone in Tech Crew for supporting each other and making it a great experience!",},
        {"id":42,"group":"Tech","name":"Grace LaFrancois","role":"Tech Crew","grade":"8","bio":"Grace LaFrancois participates in multiple extracurricular activities at school, such as River Bend Jazz, Library club, National Junior Honor Society, Odyssey of the Mind, and Tech crew. She enjoys the behind-the-scenes aspect of theatre, due to her lack of coordination and, ironically, her lack of grace. In her (extremely limited) free time, she likes to read and talk with her friends.",},
        {"id":43,"group":"Tech","name":"Cailin Flatla","role":"Tech Crew","grade":"8","bio":"Cailin likes to read, draw, hang out with friends, and play on her club volleyball team. This is Cailin's second year in tech crew, and she is very glad that she gets to be a part of the musical this year.",},
        {"id":44,"group":"Tech","name":"Jonathan Mason","role":"Tech Crew","grade":"8","bio":"I am very excited to be a part of another play this year. This is my second play that I have been a part of. I was on running crew last year as well as this year and it is a lot of fun. In my free time I like to play with my dog, read, and do CrossFit. I would like to thank all of the crew, cast, teachers, and parents who took the time to help make this show possible.",},
        {"id":45,"group":"Tech","name":"Kyle Robertson","role":"Tech Crew","grade":"8","bio":"I have had a blast helping in the production of <em>Shrek Jr.</em> When I'm not behind the stage figuring out how paint works, I like to draw, play football, and search for some random fedora I found lying around backstage. I'd like to thank the cast for working so hard, and I'd also like to thank our teachers and volunteers who managed to keep us on track.",},
        {"id":46,"group":"Tech","name":"Kaley McQuinn","role":"Tech Crew","grade":"6","bio":"This is my first year involved in the musical, and I am looking forward to continuing on into 7th and 8th grade. I have enjoyed working in tech crew, especially with the painting of the sets. I also enjoy reading, running and swimming. I would like to thank myself for all my hard work...and also thank my parents and Mr. Simonton for their support.",},
        {"id":47,"group":"Tech","name":"Hannah Cuasay","role":"Tech Crew","grade":"7","bio":"This is Hannah's first production. She is happy to meet new people in a new activity. Hannah first caught the &ldquo;theater bug&rdquo; singing <em>Into the Woods</em> (original soundtrack) on long car trips. She later became a fan of <em>Hamilton</em> and <em>Dear Evan Hansen</em>. Break a leg everyone! ",},
        {"id":48,"group":"Tech","name":"Emmanuel Ampeh","role":"Tech Crew","grade":"8","bio":"I am very excited to be in Tech Crew in this year's production of <em>Shrek Jr.</em>  I also participated in Tech Crew for the production of <em>The Lion King Jr.</em> in 7th grade. Outside of school, I enjoy biking, hiking, and playing soccer. I'd like to say thank you to Mr. Simonton, Mr. Wooldridge, all the teachers, parents, cast, and the rest of the crew for the hard work put into the show.",},
        {"id":49,"group":"Tech","name":"Riley Freck","role":"Tech Crew","grade":"8","bio":"This is Riley's second year participating in the drama production. She was part of the ensemble for <em>The Lion King Jr.</em> and is on the tech crew for <em>Shrek Jr.</em> She has enjoyed seeing the shows from both perspectives!",},
        {"id":50,"group":"Tech","name":"Saba Banaii","role":"Tech Crew","grade":"8","bio":"I was thrilled to be chosen to design and create this year's musical sets. The colorful backgrounds behind the actors was my pleasure to create. Also, I'm excited to be a stage manager. I was a member of tech crew last year, participating in the makeup and costume department. After having a wonderful experience I became interested in the managing field of tech. In my free time I enjoy to draw, write, read, participate in a variety of extra curricular and spend time with my family and friends.",},
        {"id":51,"group":"Tech","name":"Aimee Wakefield","role":"Tech Crew","grade":"8","bio":"I’m excited to be part of tech crew for <em>Shrek Jr.</em> this year.",},
        {"id":52,"group":"Tech","name":"Daliah Minkara","role":"Tech Crew","grade":"8","bio":"Daliah Minkara is in 8th grade. This is her second year doing tech crew and participating backstage as door manager. She got interested in backstage management through Odyssey of the Mind. Daliah hopes to continue tech crew in high school.",},
        {"id":53,"group":"Tech","name":"Madelyn Damore","role":"Tech Crew","grade":"8","bio":"I'm excited to help with tech crew this year for River Bend's Middle School <em>Shrek Jr.</em> musical. I was also tech crew last year for <em>The Lion King Jr.</em> and I had an amazing time so I just had to do it again this year. In my spare time, I love to draw, read, skate, and play with my two dogs. I will like to thank my fellow cast and crew members for being respectful to each other and working hard to make this play wonderful. Lastly, I'd like to thank Mr. Simonton for putting up with us and encouraging us.",},
        {"id":54,"group":"Tech","name":"Stella Navin","role":"Tech Crew","grade":"7","bio":"This is my first year doing tech crew, I am helping with costumes and painting for this years musical. When I'm not in school, I like to be creative at home. Doing things such as painting, drawing, and weaving every once in awhile.I also enjoy playing tennis and I'm on the Countryside Swim Team during the summer. I would like to thank my family for encouraging me to try harder with my art and giving me the space to do so.",},
    {"id":55,"group":"Tech","name":"Tori Lenz","role":"Tech Crew","grade":"","bio":"",},
        {"id":56,"group":"Tech","name":"Jaklin Palmer","role":"Tech Crew","grade":"6","bio":"This is my first musical. I am a lights person and it's really fun to be able to be a part of tech crew. I love the fact that we not only do lights and sound, we also do the backgrounds and help with costumes. I would like to thank the other kids in tech club for welcoming me and also Mr. Simonton and the other supervisors.",},
    {"id":57,"group":"Tech","name":"Emma Murray","role":"Tech Crew","grade":"","bio":"",},
    {"id":58,"group":"Tech","name":"Sarah Ruehl","role":"Tech Crew","grade":"","bio":"",},
        {"id":80,"group":"Cast","name":"Kara Adamson","role":"Duloc Performer","grade":"7","bio":"Kara started performing in 5th grade doing choir. She continued that into 6th grade where she also caught the acting bug and performed in the winter program, <em>The Lion King Jr.</em> Kara has 2 brothers, one older and one younger. Her father was also in theater in high school and college.",},
        {"id":81,"group":"Cast","name":"Christina Andreyko","role":"Duloc Performer","grade":"7","bio":"This is my first musical at RBMS. I am so excited to be a part of the Duloc citizens ensemble. I enjoy acting in my Christmas pageant every year at my church since 3rd grade. I also love to watch <em>Shrek The Musical</em> and sing along to it all the time. I would like to thank Mr. Simonton for teaching me more about theater.",},
        {"id":82,"group":"Cast","name":"Alexis Antonellis","role":"Duloc Performer","grade":"7","bio":"This is my second year in the school play. I love to sing and perform. When I'm not performing I love to play lacrosse and basketball. Thank you to my family for supporting me. Also thank you to Mr. Simonton for directing an awesome play.",},
        {"id":83,"group":"Cast","name":"Rebecca Bassett","role":"Duloc Performer","grade":"6","bio":"Becca is excited to participate in her first middle school production as a citizen of Duloc.  When not in school, Becca enjoys practicing for her piano recitals, competitive cheer and swimming, and helping her parents keep tabs on her younger brothers. Becca would like to express her appreciation to Mr. Simonton for his patience and dedication throughout this production.",},
        {"id":84,"group":"Cast","name":"Sophie Detorie","role":"Duloc Performer","grade":"6","bio":"This is my first musical, and I'm so happy it's Shrek. I'm looking forward to my next two years at RBMS, and you'll be seeing me in future productions. Aside from school, I play three sports: lacrosse, swim, and field hockey. I also love to read and play guitar. I'd like to thank not only the choreographers and Mr. Simonton, but also my family for their support.",},
        {"id":85,"group":"Cast","name":"Jackson Lenz","role":"Duloc Performer","grade":"6","bio":"Jackson Lenz, who plays the role of the Bishop, is participating in his first acting experience. Jackson is a sixth grader at River Bend where his favorite subjects are Science and Chorus. When not at school, Jackson enjoys hanging out and playing various games with his family and friends.",},
        {"id":86,"group":"Cast","name":"India Eriksen","role":"Duloc Performer","grade":"8","bio":"This is my debut theater performance and I could not be happier to be up on stage for the first time. I have really had fun and learned a lot about theater and music, and how patient a teacher can be when faced with a mob of Middle School theater kids. I want to thank my Mom for writing this bio and making sure I was at most of the rehearsals, and for all of the encouragement and snack reminders.",},
        {"id":87,"group":"Cast","name":"Nadia Freidson","role":"Duloc Performer","grade":"7","bio":"Since I was young, I have loved being on stage. I feel like I can transform into someone new, and the real world melts away. Even though I am only in the chorus, this is an amazing experience and I will always remember it. Last year I was a wildebeast in <em>The Lion King Jr.</em> <em>The Lion King Jr.</em> was so much fun as well! In my free time I like to dance, sing and write. I would like to thank everyone who helped make this production possible. I know it took a LOT of time and effort.",},
        {"id":88,"group":"Cast","name":"Sophia Jorgensen","role":"Duloc Performer","grade":"6","bio":"I am very happy to play the role of a Duloc villager.  I am having fun learning about how the stage works.  In my spare time, I enjoy art, music and reading.  Thanks to my family for supporting me in the play, and to Mr. Simonton for teaching me and making <em>Shrek Jr.</em> a great experience!",},
        {"id":89,"group":"Cast","name":"Jeremy LaFrancois","role":"Duloc Performer","grade":"6","bio":"Jeremy is a member of the drama club, an active Boy Scout, and participated in Odyssey of the Mind this year. In elementary school, Jeremy enjoyed participating in the class musicals. This is his first middle school production. He is very excited to be a part of the cast! In his free time, Jeremy likes to play video games.",},
        {"id":90,"group":"Cast","name":"Isabella Lewis","role":"Duloc Performer","grade":"8","bio":"Isabella is excited to be a part of the cast for <em>Shrek Jr.</em> This is her first time participating in a musical at River Bend. In her spare time she enjoys drawing, singing and reading. Isabella would like to thank everyone for their hard work, especially Mr. Simonton. A special thanks to her family for their continued support.",},
        {"id":92,"group":"Cast","name":"Lauren Schaaf","role":"Duloc Performer","grade":"6","bio":"I am excited to be a part of <em>Shrek Jr.</em> I enjoy dancing on stage as well as reading and acting. Next year, I look forward to taking more musical theater classes. I want to thank Mr. Simonton for always being so encouraging to the cast and crew. I also want to thank my Mom and Dad for always being there for me. I will never forget this experience.",},
        {"id":93,"group":"Cast","name":"Cemile Short","role":"Duloc Performer","grade":"8","bio":"Cemile likes to sing and perform. Outside of school she also sings & reads. She would like to thank her mom & dad for letting her participate, Mr.Simonton for hosting the show, & both choreographers for teaching me all my dances! ",},
        {"id":94,"group":"Cast","name":"Elise Short","role":"Duloc Performer","grade":"7","bio":"I am a duloc citizen and love king farquaad. I am perfect and will NEVER step out of line.",},
        {"id":95,"group":"Cast","name":"Isabelle Sullivan","role":"Duloc Performer","grade":"7","bio":"I was really excited to be in the musical this year! I was in tech crew last year and it was fun to learn about what goes on backstage. I did two musicals in elementary school, it was good experience and good practice. I enjoyed working on the <em>Shrek Jr.</em> musical and can't wait for next year. I would also like to thank my parents and grandparents for all of their loving support.",},
        {"id":96,"group":"Cast","name":"Safiya Suri","role":"Duloc Performer","grade":"6","bio":"I am making my theater debut as a Duloc Citizen in <em>Shrek Jr.</em> this year and it has been stressful, tiring but mostly fun! Thank you to Caileigh O., Becca, and Myla for making rehearsals hilarious. Thank you to Mr. Simonton for dealing with us.  I honestly don't know how he does it. Oh!  And my mom.",},
        {"id":97,"group":"Cast","name":"Kaelynn Watjen","role":"Duloc Performer","grade":"7","bio":"Shrek the Musical will be my 1st musical at River Bend Middle School. When I’m not on the stage, I like to practice my Tae Kwon Do, do Girl Scouts, draw, travel, ice skate, and hang out with my family. I’d like to thank my mom, my dad, siblings, cousins and my friends for supporting me when i’m rehearsing, but I’d like to especially thank Mr.Simonton for making it all come together and letting me perform for <em>Shrek Jr.</em>",},
        {"id":98,"group":"Cast","name":"Natalie Wike","role":"Duloc Performer","grade":"8","bio":"This is my second production at River Bend and I am excited to be a part of <em>Shrek Jr.</em>, this year. I've really enjoyed rehearsing with the cast and crew and can't wait for the performances. Outside of theater, I enjoy dancing and playing the violin. I would like to thank everyone that contributed to the production of the musical, especially Mr. Simonton for all of his hard work. I want to thank my parents and brother, Eli, for all of their support.",}
    ];

    $(document).ready(function(){

        // handle selection states and smooth scrolling for top navigation items
        $('.menu-items .item').click(function(el){
            var selection = $(this)
            var target = $(this).data('target')
            $('.menu-items .item').removeClass('active')
            selection.toggleClass('active')
            // reload page to force content to true top
            if (target === "home"){
                location.reload();
            } else {
                // all other elements; set selection state and smooth scroll to top of target element
                var targetEl = document.getElementById(target)
                targetEl.scrollIntoView()
                var wrapPosition = $('.content-wrapper').scrollTop()
            }
        })

        // lazy-load image content to spead up initial page load
        $('.lazy').Lazy({
            scrollDirection: 'vertical',
            effect: 'fadeIn',
            visibleOnly: true,
            onError: function(element) {
                console.log('error loading ' + element.data('src'));
            }
        });

        // load cast and tech crew lists (names, roles, headshots, bios)
        $.each(people, function(i){
            var castList = $('.castList')
            var crewList = $('.crewList')
            var participant = people[i]
            //console.log(participant)
            var name = participant['name']
            var grade = participant['grade']
            var role = participant['role']
            var bio = participant['bio']
            var headshot = name.split(" ").join("") + '.jpg'
            //console.log(headshot)
            var template = '<div class="participant" data-name="'+name+'"><a href="#profileModal" class="modalTrigger" data-bio="'+bio+'" data-grade="'+grade+'"><img src="images/headshots/'+headshot+'" /><p class="name">'+name+'</p><p class="role">'+role+'</p><p class="bio">Bio</div></div>'
            //console.log(template)
            if (participant['group'] === "Cast"){
                castList.append(template)
            } else {
                crewList.append(template)
            }
        })

        // instantiate modal pop-over
        $('a.modalTrigger').click(function(event) {
            //console.log(this)
            var headshotURL = $(this).find('img').attr('src')
            var name = $(this).find('.name').text()
            var grade = $(this).data('grade')
            var role = $(this).find('.role').text()
            var bio = $(this).data('bio')
            var modalTemplate = '<div id="profileModal"><div class="headshot"><img src="'+headshotURL+'" /></div><div class="details"><div class="name">'+name+'</div><div class="grade">Grade '+grade+'</div><div class="role">'+role+'</div></div><div class="bio">'+bio+'</div></div>'
            $(modalTemplate).appendTo('body').modal({
              fadeDuration: 100,
              fadeDelay: 2
            });
            return false;
        });

    });


})(jQuery, window, document);
